import type { Hatchery } from "./types";

export const hatcheries: Hatchery[] = [
    {
        id: 1,
        code: "GS001",
        name: "Trại giống Bình Thủy",
        owner: "Nguyễn Văn A",
        phone: "0909123456",
        ward: "Bình Thủy",
        species: "Cá tra",
        capacity: 12,
        production: 10.8,
        status: "ACTIVE",
        address: "Bình Thủy, Cần Thơ",
        licenseDate: "2024-01-15",
    },
    {
        id: 2,
        code: "GS002",
        name: "Trung tâm giống Ô Môn",
        owner: "Trần Văn B",
        phone: "0909888999",
        ward: "Ô Môn",
        species: "Tôm thẻ",
        capacity: 20,
        production: 16.5,
        status: "ACTIVE",
        address: "Ô Môn, Cần Thơ",
        licenseDate: "2023-10-01",
    },
    {
        id: 3,
        code: "GS003",
        name: "Cơ sở giống Thới Lai",
        owner: "Lê Văn C",
        phone: "0911888777",
        ward: "Thới Lai",
        species: "Cá rô phi",
        capacity: 8,
        production: 5.2,
        status: "WARNING",
        address: "Thới Lai, Cần Thơ",
        licenseDate: "2022-08-11",
    },
    {
        id: 4,
        code: "GS004",
        name: "Trại giống Cờ Đỏ",
        owner: "Phạm Văn D",
        phone: "0933777888",
        ward: "Cờ Đỏ",
        species: "Cá lóc",
        capacity: 15,
        production: 14.2,
        status: "ACTIVE",
        address: "Cờ Đỏ, Cần Thơ",
        licenseDate: "2024-04-20",
    },
    {
        id: 5,
        code: "GS005",
        name: "Trại giống Phong Điền",
        owner: "Nguyễn Thị H",
        phone: "0977555666",
        ward: "Phong Điền",
        species: "Cá điêu hồng",
        capacity: 10,
        production: 6.3,
        status: "INACTIVE",
        address: "Phong Điền, Cần Thơ",
        licenseDate: "2021-12-30",
    },
];